apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-management
  template:
    metadata:
      labels:
        app: user-management
    spec:
      containers:
        - name: user-management
          image: 767660394878.dkr.ecr.us-west-2.amazonaws.com/user-management-service-20211121013430:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3015
          env:
            - name: AWS_REGION
              value: "us-west-2"
            - name: COGNITO_USER_POOL_ID
              value: "us-west-2_usHVFRp9C"
---
apiVersion: v1
kind: Service
metadata:
  name: user-management
spec:
  selector:
    app: user-management
  ports:
    - name: http
      protocol: TCP
      port: 3015
      targetPort: 3015
